# Usar una imagen base de Node.js
FROM node:20-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app/backend

# Copiar package.json y package-lock.json para instalar dependencias
COPY backend/package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código de la aplicación
COPY backend/. .

# Exponer el puerto en el que la aplicación Express se ejecutará
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "start"]
